# Runs a consul-backed Vault server
version: '2'
services:
  consul:
    image: progrium/consul
    container_name: consul
    command: ["-server", "-bootstrap"]
  vault:
    image: elcolio/vault
    container_name: vault
    links:
      - 'consul:consul'
    ports:
      - '8200:8200'
    restart: always
    environment:
      VAULT_BACKEND: consul
      VAULT_BACKEND_ADDRESS: consul:8500
      VAULT_BACKEND_SCHEME: http
      VAULT_BACKEND_ADVERTISE_ADDR: http://127.0.0.1:8200
      VAULT_BACKEND_PATH: /vault